### ISSUE TITLE
Error after first install

### ISSUE THREAD

**Issue by aldodemi** [MarcelSlabosz/domoticz_sonoff_ewelink_api_plugin#4]
Error after first install:

domoticz@domoserver:~/domoticz/plugins/sonoff_ewelink$ node -v
v12.20.2
domoticz@domoserver:~/domoticz/plugins/sonoff_ewelink$ node get_credentials.js
Obtaining credentials...
(node:1864901) UnhandledPromiseRejectionWarning: FetchError: request to https://it-api.coolkit.cc:8080/api/user/login failed, reason: getaddrinfo ENOTFOUND it-api.coolkit.cc
    at ClientRequest.<anonymous> (/home/domoticz/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketErrorListener (_http_client.js:427:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1864901) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1864901) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Credential are correct

Thank you
Aldo

**Comment by aldodemi** [comment]
The error was the "region" definition, I originaly put "it" the correct one was "eu".
