### ISSUE TITLE
invalid json response body

### ISSUE THREAD

**Issue by Vincent835** [MarcelSlabosz/domoticz_sonoff_ewelink_api_plugin#5]
Hi,

I have an error to get credentials.

> pi@raspberrypi:~/domoticz/plugins/domoticz_sonoff_ewelink $ node get_credentials.js
> Obtaining credentials...
> 
> /home/pi/node_modules/node-fetch/lib/index.js:273
>                                 return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.messag          e}`, 'invalid-json'));
>                                                            ^
> FetchError: invalid json response body at https://eu-api.coolkit.cc:8080/api/user/login reason: Unexpected token < in JSON at position 0
>     at /home/pi/node_modules/node-fetch/lib/index.js:273:32
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async eWeLink.getCredentials (/home/pi/node_modules/ewelink-api/src/mixins/getCredentials.js:32:20)
>     at async /home/pi/domoticz/plugins/domoticz_sonoff_ewelink/get_credentials.js:9:18 {
>   type: 'invalid-json'
> }

thank you

Vincent

**Comment by Vincent835** [comment]
perhaps an error in my login.
